version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: it-helpdesk-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helpdesk
    ports:
      - "5432:5432"
    volumes:
      - helpdesk_pg_data:/var/lib/postgresql/data

volumes:
  helpdesk_pg_data:
